### ISSUE TITLE
NullPointerException: Attempt to invoke virtual method 'int android.util.Size.getWidth()' on a null object reference

### ISSUE THREAD

**Issue by kw2019ltd** [santetis/flutter_camera_ml_vision#120]
```
getting below iam using latest version:

1.0.0 (27) 7.0 Galaxy S9 Jun 23, 2020, 11:18:00 AM 
![image](https://user-images.githubusercontent.com/47334522/85455867-0a962780-b5a7-11ea-8a9c-3c09f19a32e7.png)


Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.util.Size.getWidth()' on a null object reference
       at android.hardware.camera2.legacy.LegacyCameraDevice.configureOutputs(LegacyCameraDevice.java:371)
       at android.hardware.camera2.legacy.CameraDeviceUserShim.endConfigure(CameraDeviceUserShim.java:511)
       at android.hardware.camera2.impl.ICameraDeviceUserWrapper.endConfigure(ICameraDeviceUserWrapper.java:111)
       at android.hardware.camera2.impl.CameraDeviceImpl.configureStreamsChecked(CameraDeviceImpl.java:456)
       at android.hardware.camera2.impl.CameraDeviceImpl.createCaptureSessionInternal(CameraDeviceImpl.java:607)
       at android.hardware.camera2.impl.CameraDeviceImpl.createCaptureSession(CameraDeviceImpl.java:491)
       at io.flutter.plugins.camera.Camera.createCaptureSession(Camera.java:344)
       at io.flutter.plugins.camera.Camera.createCaptureSession(Camera.java:283)
       at io.flutter.plugins.camera.Camera.startPreview(Camera.java:424)
       at io.flutter.plugins.camera.Camera$2.onOpened(Camera.java:160)
       at android.hardware.camera2.impl.CameraDeviceImpl$1.run(CameraDeviceImpl.java:134)
       at android.os.Handler.handleCallback(Handler.java:836)
       at android.os.Handler.dispatchMessage(Handler.java:103)
       at android.os.Looper.loop(Looper.java:203)
       at android.app.ActivityThread.main(ActivityThread.java:6251)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1063)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:924)
```

**Comment by kw2019ltd** [comment]
![image](https://user-images.githubusercontent.com/47334522/85455953-1f72bb00-b5a7-11ea-9714-a76093f95326.png)

**Comment by jaumard** [comment]
Hum look like a bug into camera plugin not ours. Please try last version we updated the camera plugin, if it's the same I suggest you open an issue on camera plugin directly
