### ISSUE TITLE
Dynamically change resolution

### ISSUE THREAD

**Issue by Endebert** [santetis/flutter_camera_ml_vision#74]
In my app, I have a settings view where the user can change the camera resolution for this plugin. The user can navigate to the settings via a button, and when they return, the resolution should update. Because of that, I wrapped your widget with a Streambuilder, updating the widget with the latest resolution state.

Unfortunately, this seems to not be supported. Do you by chance know of a workaround to achieve this?

This is a snippet from my code:
```dart
StreamBuilder<ResolutionPreset>(
  stream: StateBloc.instance.cameraResolution,
  initialData: StateBloc.instance.cameraResolution.value,
  builder: (context, snapshot) {
    return RotatedBox(
      quarterTurns: MediaQuery.of(context).orientation == Orientation.landscape ? 1 : 0,
      child: CameraMlVision<List<Barcode>>(
        resolution: StateBloc.instance.cameraResolution.value,
        detector: FirebaseVision.instance.barcodeDetector().detectInImage,
        onResult: (List<Barcode> barcodes) {
          // do something
        },
        loadingBuilder: (context) => loadingOverlay(context),
      ),
    );
  },
),
```

**Comment by kevin-sakemaer** [comment]
Can you try to put an `UniqueKey` on `CameraMlVision` ?

**Comment by Endebert** [comment]
Thanks for the quick reply! This works, but causes an exception related to `setState()`:

```
I/flutter (26659): 2019-09-09 11:08:04.678752 SEVERE  : Uncaught exception thrown! setState() called after dispose(): CameraMlVisionState<List<Barcode>>#2f005(lifecycle state: defunct, not mounted)
I/flutter (26659): This error happens if you call setState() on a State object for a widget that no longer appears in the widget tree (e.g., whose parent widget no longer includes the widget in its build). This error can occur when code calls setState() from a timer or an animation callback.
I/flutter (26659): The preferred solution is to cancel the timer or stop listening to the animation in the dispose() callback. Another solution is to check the "mounted" property of this object before calling setState() to ensure the object is still in the tree.
I/flutter (26659): This error might indicate a memory leak if setState() is being called because another object is retaining a reference to this State object after it has been removed from the tree. To avoid memory leaks, consider breaking the reference to this object during dispose().
I/flutter (26659): #0      State.setState.<anonymous closure> (package:flutter/src/widgets/framework.dart:1105:9)
I/flutter (26659): #1      State.setState (package:flutter/src/widgets/framework.dart:1140:6)
I/flutter (26659): #2      CameraMlVisionState._initialize (package:flutter_camera_ml_vision/flutter_camera_ml_vision.dart:182:7)
I/flutter (26659): <asynchronous suspension>
I/flutter (26659): #3      CameraMlVisionState.initState (package:flutter_camera_ml_vision/flutter_camera_ml_vision.dart:75:5)
I/flutter (26659): #4      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4033:58)
I/flutter (26659): #5      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3902:5)
I/flutter (26659): #6      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
I/flutter (26659): #7      Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
I/flutter (26659): #8      SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5099:14)
I/flutter (26659): #9      Element.updateChild (package:flutter/src/widgets/framework.dart:2876:15)
I/flutter (26659): #10     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
...
```

**Comment by kevin-sakemaer** [comment]
could you move the 2 debugPrint [here](https://github.com/rushio-consulting/flutter_camera_ml_vision/blob/master/lib/flutter_camera_ml_vision.dart#L186) above setState ? and give us the output ?

**Comment by Endebert** [comment]
When I initially open the view with your widget, I get two errors:

(1) (contains your debug prints)
```
I/flutter (31330): Can't initialize camera
I/flutter (31330): A CameraController was used after being disposed.
I/flutter (31330): Once you have called dispose() on a CameraController, it can no longer be used., #0      ChangeNotifier._debugAssertNotDisposed.<anonymous closure> (package:flutter/src/foundation/change_notifier.dart:105:9)
I/flutter (31330): #1      ChangeNotifier._debugAssertNotDisposed (package:flutter/src/foundation/change_notifier.dart:111:6)
I/flutter (31330): #2      ChangeNotifier.notifyListeners (package:flutter/src/foundation/change_notifier.dart:200:12)
I/flutter (31330): #3      ValueNotifier.value= (package:flutter/src/foundation/change_notifier.dart:273:5)
I/flutter (31330): #4      CameraController.initialize (package:camera/camera.dart:280:7)
I/flutter (31330): <asynchronous suspension>
I/flutter (31330): #5      CameraMlVisionState._initialize (package:flutter_camera_ml_vision/flutter_camera_ml_vision.dart:180:31)
I/flutter (31330): <asynchronous suspension>
I/flutter (31330): #6      CameraMlVisionState.initState (package:flutter_camera_ml_vision/flutter_camera_ml_vision.dart:75:5)
I/flutter (31330): #7      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4033:58)
I/flutter (31330): #8      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3902:5)
I/flutter (31330): #9      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
I/flutter (31330): #10     Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
```

(2)
```
I/flutter (31330): 2019-09-09 11:19:21.978651 SEVERE  : Uncaught exception thrown! setState() called after dispose(): CameraMlVisionState<List<Barcode>>#ccc5a(lifecycle state: defunct, not mounted)
I/flutter (31330): This error happens if you call setState() on a State object for a widget that no longer appears in the widget tree (e.g., whose parent widget no longer includes the widget in its build). This error can occur when code calls setState() from a timer or an animation callback.
I/flutter (31330): The preferred solution is to cancel the timer or stop listening to the animation in the dispose() callback. Another solution is to check the "mounted" property of this object before calling setState() to ensure the object is still in the tree.
I/flutter (31330): This error might indicate a memory leak if setState() is being called because another object is retaining a reference to this State object after it has been removed from the tree. To avoid memory leaks, consider breaking the reference to this object during dispose().
I/flutter (31330): #0      State.setState.<anonymous closure> (package:flutter/src/widgets/framework.dart:1105:9)
I/flutter (31330): #1      State.setState (package:flutter/src/widgets/framework.dart:1140:6)
I/flutter (31330): #2      CameraMlVisionState._initialize (package:flutter_camera_ml_vision/flutter_camera_ml_vision.dart:184:7)
I/flutter (31330): <asynchronous suspension>
I/flutter (31330): #3      CameraMlVisionState.initState (package:flutter_camera_ml_vision/flutter_camera_ml_vision.dart:75:5)
I/flutter (31330): #4      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4033:58)
```

Then again, when I return from the settings view:

```
I/flutter (31330): 2019-09-09 11:21:38.388304 SEVERE  : Uncaught exception thrown! CameraException(A camera has started streaming images., startImageStream was called while a camera was streaming images.)
I/flutter (31330): #0      CameraController.startImageStream (package:camera/camera.dart:394:7)
I/flutter (31330): <asynchronous suspension>
I/flutter (31330): #1      CameraMlVisionState._start (package:flutter_camera_ml_vision/flutter_camera_ml_vision.dart:119:23)
I/flutter (31330): #2      CameraMlVisionState.deactivate (package:flutter_camera_ml_vision/flutter_camera_ml_vision.dart:208:9)
I/flutter (31330): #3      StatefulElement.deactivate (package:flutter/src/widgets/framework.dart:4100:12)
I/flutter (31330): #4      _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1755:13)
```

**Comment by abheet-98** [comment]
@Endebert Heyy !
Hope you are doing well.
Hello !
Have you got the method to change the resolution of the video(sd/hd/fhd) that streams from the app to the server.

I'm working on a live streaming app and I want that user can itself change the resolution (video quality) of its stream.
Thanks in advance !
