### ISSUE TITLE
Error handling on vision library download fail

### ISSUE THREAD

**Issue by saddy001** [santetis/flutter_camera_ml_vision#77]
There is a known issue when using the on-device vision library where it doesn't download in some cases. One can trigger this by uninstalling the app, clearing all data of play services and then launching the app again while having no internet access. Basically this is a won't fix from google so we have to deal with it in some way, because the end user just sees: "doesn't work, crap". I tried to use 

```
CameraMlVision...
errorBuilder: (context, e) => Center(
          child: Text('Error appear!'),
        ),
```

But it isn't triggered. How can we deal with this?

PS: On Android, the best known workaround is here: https://stackoverflow.com/questions/52855632/firebase-ml-kit-give-firebasemlexception-waiting-for-the-text-recognition-model/52929144#52929144

But I couldn't get this working on flutter.

The error messages are

```
Launching lib/main.dart on SM G950F in debug mode...
Initializing gradle...
Resolving dependencies...
Running Gradle task 'assembleDebug'...
Note: /home/test/.pub-cache/hosted/pub.dartlang.org/url_launcher-5.1.3/android/src/main/java/io/flutter/plugins/urllauncher/WebViewActivity.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Built build/app/outputs/apk/debug/app-debug.apk.
Installing build/app/outputs/apk/app.apk...
D/SurfaceView(22372): surfaceChanged (1080,2076) 1 #8 io.flutter.view.FlutterView{a2a14db VFE...... ......ID 0,0-1080,2076}
Syncing files to device SM G950F...
D/ViewRootImpl@b66128c[MainActivity](22372): Relayout returned: old=[0,0][1080,2220] new=[0,0][1080,2220] result=0x3 surface={valid=true 540283871232} changed=false
D/vndksupport(22372): Loading /vendor/lib64/hw/android.hardware.graphics.mapper@2.0-impl.so from current namespace instead of sphal namespace.
D/ViewRootImpl@b66128c[MainActivity](22372): MSG_WINDOW_FOCUS_CHANGED 1 1
D/InputMethodManager(22372): prepareNavigationBarInfo() DecorView@13fac7[MainActivity]
D/InputMethodManager(22372): getNavigationBarColor() -855310
D/InputMethodManager(22372): prepareNavigationBarInfo() DecorView@13fac7[MainActivity]
D/InputMethodManager(22372): getNavigationBarColor() -855310
V/InputMethodManager(22372): Starting input: tba=test.test ic=null mNaviBarColor -855310 mIsGetNaviBarColorSuccess true , NavVisible : true , NavTrans : false
D/InputMethodManager(22372): startInputInner - Id : 0
I/InputMethodManager(22372): startInputInner - mService.startInputOrWindowGainedFocus
D/InputTransport(22372): Input channel constructed: fd=94
D/ViewRootImpl@b66128c[MainActivity](22372): MSG_RESIZED_REPORT: frame=Rect(0, 0 - 1080, 2220) ci=Rect(0, 72 - 0, 144) vi=Rect(0, 72 - 0, 144) or=1
D/InputMethodManager(22372): prepareNavigationBarInfo() DecorView@13fac7[MainActivity]
D/InputMethodManager(22372): getNavigationBarColor() -855310
V/InputMethodManager(22372): Starting input: tba=test.test ic=null mNaviBarColor -855310 mIsGetNaviBarColorSuccess true , NavVisible : true , NavTrans : false
D/InputMethodManager(22372): startInputInner - Id : 0
I/System.out(22372): Keeping screen on 
D/ViewRootImpl@b66128c[MainActivity](22372): Relayout returned: old=[0,0][1080,2220] new=[0,0][1080,2220] result=0x1 surface={valid=true 540283871232} changed=false
I/flutter (22372): [2019-09-21 10:43:27.124077 | Catcher | FINE] Using debug config
I/flutter (22372): [2019-09-21 10:43:28.475311 | Catcher | FINE] Catcher configured successfully.
I/CameraManagerGlobal(22372): Connecting to camera service
D/VendorTagDescriptor(22372): addVendorDescriptor: vendor tag id 3854507339 added
D/ViewRootImpl@b66128c[MainActivity](22372): MSG_WINDOW_FOCUS_CHANGED 0 1
D/InputMethodManager(22372): prepareNavigationBarInfo() DecorView@13fac7[MainActivity]
D/InputMethodManager(22372): getNavigationBarColor() -855310
D/InputTransport(22372): Input channel destroyed: fd=94
D/SensorManager(22372): registerListener :: 6, LSM6DSL Acceleration Sensor, 200000, 0,  
D/ViewRootImpl@b66128c[MainActivity](22372): setWindowStopped(false) old=false
D/ViewRootImpl@b66128c[MainActivity](22372): MSG_WINDOW_FOCUS_CHANGED 1 1
D/InputMethodManager(22372): prepareNavigationBarInfo() DecorView@13fac7[MainActivity]
D/InputMethodManager(22372): getNavigationBarColor() -855310
D/InputMethodManager(22372): prepareNavigationBarInfo() DecorView@13fac7[MainActivity]
D/InputMethodManager(22372): getNavigationBarColor() -855310
V/InputMethodManager(22372): Starting input: tba=test.test ic=null mNaviBarColor -855310 mIsGetNaviBarColorSuccess true , NavVisible : true , NavTrans : false
D/InputMethodManager(22372): startInputInner - Id : 0
I/InputMethodManager(22372): startInputInner - mService.startInputOrWindowGainedFocus
D/InputTransport(22372): Input channel constructed: fd=105
W/System  (22372): A resource failed to call release. 
W/DynamiteModule(22372): Local module descriptor class for com.google.android.gms.vision.dynamite.text not found.
I/DynamiteModule(22372): Considering local module com.google.android.gms.vision.dynamite.text:0 and remote module com.google.android.gms.vision.dynamite.text:0
D/TextNativeHandle(22372): Cannot load feature, fall back to load whole module.
W/DynamiteModule(22372): Local module descriptor class for com.google.android.gms.vision.dynamite not found.
W/lnerapps.test(22372): Unsupported class loader
W/lnerapps.test(22372): Skipping duplicate class check due to unsupported classloader
I/DynamiteModule(22372): Considering local module com.google.android.gms.vision.dynamite:0 and remote module com.google.android.gms.vision.dynamite:2702
I/DynamiteModule(22372): Selected remote version of com.google.android.gms.vision.dynamite, version >= 2702
V/DynamiteModule(22372): Dynamite loader version >= 2, using loadModule2NoCrashUtils
W/lnerapps.test(22372): Accessing hidden field Ljava/nio/Buffer;->address:J (light greylist, reflection)
W/ChimeraDebugLogger(22372): Singleton logger instance not set.
W/lnerapps.test(22372): Unsupported class loader
W/lnerapps.test(22372): Skipping duplicate class check due to unsupported classloader
I/Vision  (22372): Loading library libocr.so
I/lnerapps.test(22372): The ClassLoaderContext is a special shared library.
I/chatty  (22372): uid=10289(test.test) FirebaseMLHandl identical 1 line
I/lnerapps.test(22372): The ClassLoaderContext is a special shared library.
W/lnerapps.test(22372): Accessing hidden method Ldalvik/system/VMRuntime;->getRuntime()Ldalvik/system/VMRuntime; (light greylist, reflection)
W/lnerapps.test(22372): Accessing hidden method Ldalvik/system/VMRuntime;->is64Bit()Z (light greylist, reflection)
I/Vision  (22372): Library not found: /data/user/0/com.google.android.gms/app_vision/ocr/libs/arm64-v8a/libocr.so
I/Vision  (22372): libocr.so library load status: false
I/Vision  (22372): Request download for engine ocr
W/TextNativeHandle(22372): Native handle not yet available. Reverting to no-op handle.
W/DynamiteModule(22372): Local module descriptor class for com.google.android.gms.vision.dynamite.text not found.
I/DynamiteModule(22372): Considering local module com.google.android.gms.vision.dynamite.text:0 and remote module com.google.android.gms.vision.dynamite.text:0
D/TextNativeHandle(22372): Cannot load feature, fall back to load whole module.
W/DynamiteModule(22372): Local module descriptor class for com.google.android.gms.vision.dynamite not found.
I/DynamiteModule(22372): Considering local module com.google.android.gms.vision.dynamite:0 and remote module com.google.android.gms.vision.dynamite:2702
I/DynamiteModule(22372): Selected remote version of com.google.android.gms.vision.dynamite, version >= 2702
V/DynamiteModule(22372): Dynamite loader version >= 2, using loadModule2NoCrashUtils
I/Vision  (22372): Loading library libocr.so
I/Vision  (22372): libocr.so library load status: false
I/Vision  (22372): Request download for engine ocr is a no-op because rate limiting
I/flutter (22372): PlatformException(textRecognizerError, Waiting for the text recognition model to be downloaded. Please wait., null), #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569:7)
I/flutter (22372): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:316:33)
I/flutter (22372): <asynchronous suspension>
I/flutter (22372): #2      MethodChannel.invokeMapMethod (package:flutter/src/services/platform_channel.dart:344:48)
I/flutter (22372): <asynchronous suspension>
I/flutter (22372): #3      TextRecognizer.processImage (package:firebase_ml_vision/src/text_recognizer.dart:40:38)
I/flutter (22372): <asynchronous suspension>
I/flutter (22372): #4      _detect (package:flutter_camera_ml_vision/utils.dart:43:25)
I/flutter (22372): <asynchronous suspension>
I/flutter (22372): #5      CameraMlVisionState._processImage (package:flutter_camera_ml_vision/flutter_camera_ml_vision.dart:267:33)
I/flutter (22372): <asynchronous suspension>
I/flutter (22372): #6      CameraController.startImageStream.<anonymous closure> (package:camera/camera.dart:411:20)
I/flutter (22372): #7      _rootRunUnary (dart:async/zone.dart:1132:38)
I/flutter (22372): #8      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
I/flutter (22372): #9      _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
I/flutter (22372): #10     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
I/flutter (22372): #11     _DelayedData.perform (dart:async/stream_impl.dart:591:14)
I/flutter (22372): #12     _StreamImplEvents.handleNext (dart:async/stream_impl.dart:707:11)
I/flutter (22372): #13     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:667:7)
I/flutter (22372): #14     _rootRun (dart:async/zone.dart:1120:38)
I/flutter (22372): #15     _CustomZone.run (dart:async/zone.dart:1021:19)
I/flutter (22372): #16     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
I/flutter (22372): #17     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
I/flutter (22372): #18     _rootRun (dart:async/zone.dart:1124:13)
I/flutter (22372): #19     _CustomZone.run (dart:async/zone.dart:1021:19)
I/flutter (22372): #20     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
I/flutter (22372): #21     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
I/flutter (22372): #22     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
I/flutter (22372): #23     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
I/flutter (22372): 
W/DynamiteModule(22372): Local module descriptor class for com.google.android.gms.vision.dynamite.text not found.
I/DynamiteModule(22372): Considering local module com.google.android.gms.vision.dynamite.text:0 and remote module com.google.android.gms.vision.dynamite.text:0
D/TextNativeHandle(22372): Cannot load feature, fall back to load whole module.
W/DynamiteModule(22372): Local module descriptor class for com.google.android.gms.vision.dynamite not found.
I/DynamiteModule(22372): Considering local module com.google.android.gms.vision.dynamite:0 and remote module com.google.android.gms.vision.dynamite:2702
I/DynamiteModule(22372): Selected remote version of com.google.android.gms.vision.dynamite, version >= 2702
V/DynamiteModule(22372): Dynamite loader version >= 2, using loadModule2NoCrashUtils
I/Vision  (22372): Loading library libocr.so
I/Vision  (22372): libocr.so library load status: false
I/Vision  (22372): Request download for engine ocr is a no-op because rate limiting
I/flutter (22372): PlatformException(textRecognizerError, Waiting for the text recognition model to be downloaded. Please wait., null), #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569:7)
I/flutter (22372): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:316:33)
I/flutter (22372): <asynchronous suspension>
I/flutter (22372): #2      MethodChannel.invokeMapMethod (package:flutter/src/services/platform_channel.dart:344:48)
I/flutter (22372): <asynchronous suspension>
I/flutter (22372): #3      TextRecognizer.processImage (package:firebase_ml_vision/src/text_recognizer.dart:40:38)
I/flutter (22372): <asynchronous suspension>
I/flutter (22372): #4      _detect (package:flutter_camera_ml_vision/utils.dart:43:25)
I/flutter (22372): <asynchronous suspension>
I/flutter (22372): #5      CameraMlVisionState._processImage (package:flutter_camera_ml_vision/flutter_camera_ml_vision.dart:267:33)
I/flutter (22372): <asynchronous suspension>
I/flutter (22372): #6      CameraController.startImageStream.<anonymous closure> (package:camera/camera.dart:411:20)
I/flutter (22372): #7      _rootRunUnary (dart:async/zone.dart:1132:38)
I/flutter (22372): #8      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
I/flutter (22372): #9      _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
I/flutter (22372): #10     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
I/flutter (22372): #11     _DelayedData.perform (dart:async/stream_impl.dart:591:14)
I/flutter (22372): #12     _StreamImplEvents.handleNext (dart:async/stream_impl.dart:707:11)
I/flutter (22372): #13     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:667:7)
I/flutter (22372): #14     _rootRun (dart:async/zone.dart:1120:38)
I/flutter (22372): #15     _CustomZone.run (dart:async/zone.dart:1021:19)
I/flutter (22372): #16     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
I/flutter (22372): #17     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
I/flutter (22372): #18     _rootRun (dart:async/zone.dart:1124:13)
I/flutter (22372): #19     _CustomZone.run (dart:async/zone.dart:1021:19)
I/flutter (22372): #20     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
I/flutter (22372): #21     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
I/flutter (22372): #22     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
I/flutter (22372): #23     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
I/flutter (22372): 
```

**Comment by jaumard** [comment]
Hi @saddy001 unfortunately here we use flutter plugins directly, this kind of fix can be done only in native side, so I suggest you ask flutter team to add support to this use case directly on firebase_ml_vision package. We can't do anything on this one I think :/
