### ISSUE TITLE
'List<dynamic>' is not a subtype of type 'Map<dynamic, dynamic>'

### ISSUE THREAD

**Issue by eimantas1998** [santetis/flutter_camera_ml_vision#90]
Hello, when i try to scan the first time everything works as expected, but when i try to do it again i get this error on a loop.

```
I/flutter (13206): type 'List<dynamic>' is not a subtype of type 'Map<dynamic, dynamic>' in type cast, #0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:321:56)
I/flutter (13206): <asynchronous suspension>
I/flutter (13206): #1      MethodChannel.invokeMapMethod (package:flutter/src/services/platform_channel.dart:349:48)
I/flutter (13206): #2      TextRecognizer.processImage (package:firebase_ml_vision/src/text_recognizer.dart:40:38)
I/flutter (13206): #3      _detect (package:flutter_camera_ml_vision/utils.dart:43:25)
I/flutter (13206): #4      CameraMlVisionState._processImage (package:flutter_camera_ml_vision/flutter_camera_ml_vision.dart:285:19)
I/flutter (13206): #5      CameraController.startImageStream.<anonymous closure> (package:camera/camera.dart:411:20)
I/flutter (13206): #6      _rootRunUnary (dart:async/zone.dart:1134:38)
I/flutter (13206): #7      _CustomZone.runUnary (dart:async/zone.dart:1031:19)
I/flutter (13206): #8      _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
I/flutter (13206): #9      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:338:11)
I/flutter (13206): #10     _DelayedData.perform (dart:async/stream_impl.dart:593:14)
I/flutter (13206): #11     _StreamImplEvents.handleNext (dart:async/stream_impl.dart:709:11)
I/flutter (13206): #12     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:669:7)
I/flutter (13206): #13     _rootRun (dart:async/zone.dart:1122:38)
I/flutter (13206): #14     _CustomZone.run (dart:async/zone.dart:1023:19)
I/flutter (13206): #15     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
I/flutter (13206): #16     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
I/flutter (13206): #17     _rootRun (dart:async/zone.dart:1126:13)
I/flutter (13206): #18     _CustomZone.run (dart:async/zone.dart:1023:19)
I/flutter (13206): #19     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
I/flutter (13206): #20     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
I/flutter (13206): #21     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
I/flutter (13206): #22     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
```

**Comment by jaumard** [comment]
Hello,

Would be nice to have a reproducible code we can copy / paste to reproduce this issue. I use it and don't have this problem, so maybe a detector I didn't use yet or a config issue. 

Thanks

**Comment by eimantas1998** [comment]
icon: Icon(Icons.photo_camera),
                        onPressed: () async {
                          String result =
                              await Navigator.of(context).push<String>(
                            MaterialPageRoute(
                              builder: (c) {
                                return ScanPage(
                                    regPattern: pattern);
                              },
                            ),
                          );
                          if ((result ?? '').isNotEmpty) {
                            _controller.text = result;
                          }

class ScanPage extends StatefulWidget {
  final String regPattern;

  ScanPage({@required this.regPattern});

  @override
  _ScanPageState createState() => _ScanPageState();
}

class _ScanPageState extends State<ScanPage> {
  TextRecognizer textRecognizer;

  bool resultSent = false;

  @override
  void initState() {
    super.initState();
    textRecognizer = FirebaseVision.instance.textRecognizer();
  }

  @override
  void dispose() {
    textRecognizer.close();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Scanner'),
      ),
      body: SafeArea(
          child: SizedBox(
              width: MediaQuery.of(context).size.width,
              height: MediaQuery.of(context).size.height,
              child: CameraMlVision<VisionText>(
                resolution: ResolutionPreset.medium,
                detector: textRecognizer.processImage,
                onResult: (VisionText visionText) {
                  String matchedText = findMatch(visionText?.blocks ?? []);
                  if (matchedText.isNotEmpty && mounted && !resultSent) {
                    setState(() {
                      resultSent = true;
                    });
                    Navigator.of(context).pop<String>(matchedText);
                  }
                },
              ))),
    );
  }

  String findMatch(List<TextBlock> textBlocks) {
    RegExp exp = new RegExp(widget.regPattern);

    String wholeText = "";
    for (TextBlock block in textBlocks) {
      block.lines.forEach((ln) => wholeText += "/" + ln.text);
    }

    if (exp.hasMatch(wholeText)) {
      return exp.stringMatch(wholeText);
    } else {
      return '';
    }
  }
}

**Comment by eimantas1998** [comment]
To reproduce the issue try to get the result, or press back button, then try to scan again. After that it just starts looping the error.
